### ISSUE TITLE
Is it suitable for webpack lazyload?

### ISSUE THREAD

**Issue by brandonxiang** [badrap/preload#1]
Webpack lazyload is used in major webapp project. So is it suitable for webpack lazyload?

**Comment by jviide** [comment]
Yes, it should be suitable. In fact we here at Badrap do use this package with lazy loaded routes (the way https://router.vuejs.org/guide/advanced/lazy-loading.html describes). Is this what you mean?

**Comment by jviide** [comment]
To add to the previous comment: We use this package with https://github.com/badrap/routdir with lazy loading as [described in routdir's README](https://github.com/badrap/routdir#setup).

**Comment by jviide** [comment]
Update: preload v0.0.5 fixes compatibility with transpiled & lazy loaded ES6 modules - see issue #2.
