### ISSUE TITLE
when use lazy loading routes in vue-cli, the preload function doesnt be executed

### ISSUE THREAD

**Issue by diem98** [badrap/preload#2]
when i use lazy loading routes in a vue demo with preload, seems that preload function doesnt be excuted.

```js
// router.js
import Vue from 'vue'
import Router from 'vue-router'
import Home from './views/Home.vue'
import preload from '@badrap/preload'

import Bar from './views/Bar'

Vue.use(Router)

export default new Router({
  routes: preload([
    {
      path: '/',
      name: 'home',
      component: Home
    },
    {
      path: '/bar',
      name: 'bar',
      component: Bar
    },
    {
      path: '/about',
      name: 'about',
      component: () => import('./views/About.vue')
    }
  ])
})

```

routes are defiend as above,  Bar component performed as excepted, but About component doesnt execute preload function 

```js
// About.vue
<template>
    <p>{{ greeting }} {{ ip}}</p>
</template>

<script>
export default {
    name: 'foo',
    data() {
        return {
            greeting: 'Hello',
            ip: 'ip from data'
        }
    },
    async preload() {
       console.log('preload ---- about.vue')
       const data = await new Promise(resolve => {
            setTimeout(() => resolve('127.0.0.1'), 3000)
        }) 
       return { ip: data}
    },
    async created() {
        console.log('created')
       
    }
}
</script>
```
when consolo.log(resolved) in preload's cachedPrepare function, seems Component Bar is different from Foo.

![dynamic](https://raw.githubusercontent.com/diem98/assets/master/images/preload-issue-dynamic-import.png)

![normal](https://raw.githubusercontent.com/diem98/assets/master/images/preload-issue-normal-import.png)

seems that import('./About.vue') resolved a esmodule, but the examples in codesandbox is ok, I don't know if it is the impact of the configuration file. babel.config.js as below:

```js
module.exports = {
  presets: ['@babel/preset-env'],
  plugins: [
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-transform-runtime'
  ]
}
```

**Comment by jviide** [comment]
Good catch! The problem is indeed that preload should assume the loaded object is an ES6 module when the `__esModule` flag is set. Published version v0.0.5 to npm, containing commit 8281a59463ac24902b20c7a7cca2851efdd7344a that should fix the problem.

**Comment by jviide** [comment]
I tested the setup that you described (preload updated to v0.0.5) in CodeSandbox. It seemed to do the trick. Does the fix work for you?

**Comment by diem98** [comment]
good job！ but what confused me is that it is ok in [codesandbox.io](https://codesandbox.io/s/3x05xw4wqp) use preload v0.04

**Comment by jviide** [comment]
Ah, true. It seems that in CodeSandbox lazy loading About.vue gives `{preload: function preload(), created: function created(), ...}`, which works even without the fix, instead of `{__esModule: true, default: {preload: function preload(),  created: function created(), ...}, ...}` .

**Comment by jviide** [comment]
I think this issue can be closed :) Thanks!
