### ISSUE TITLE
when lazy load components failed temporarily, should send fresh request next time

### ISSUE THREAD

**Issue by diem98** [badrap/preload#3]
### current behavior

![error in console](https://raw.githubusercontent.com/diem98/assets/master/images/preload-issue-import-error.png)

![error in network](https://raw.githubusercontent.com/diem98/assets/master/images/preload-issue-import-error-2.png)

you can see that 0.js only request once even though click multi times, and  it still doesn’t send request after the network is ready. 

### expected behavior
send fresh request when encounter a temporary error. 

can i pull a request to fix this problem， [my solution is here!  :)](https://github.com/diem98/preload/commit/1ee1ea5d5613d80a24f5bd6d0ff6f77f1ba6af0a)

**Comment by jviide** [comment]
Great idea, and your solution looks good! If you can make a pull request that'd be much appreciated.
